# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocks
- type: webfuzzsub
  options:
    url: https://cdn.jsdelivr.net/gh/fdaf123/KinhDown-dingyue/README.md
# 订阅链接
- type: subscribe
  options:
    url: https://sagiri.xyz/api/v1/client/subscribe?token=3629ed0a58610dac16b117d14eb848a8
- type: subscribe
  options:
    url: https://thirsty-galileo-395801.netlify.app
- type: subscribe
  options:
    url: https://sub.huojian987.site/link/rMbHxZusF1XGXXad?sub=3
- type: subscribe
  options:
    url: https://kkkssr.xyz//link/K5pwQwMMoeWguVNV?sub=1
- type: subscribe
  options:
    url: https://sub.prprc.xyz/link/heJdxuEK1sErsCEi?sub=1&class=3
- type: subscribe
  options:
    url: https://dingyue.suying666.info/link/qYopsRimEzj5qZwv?sub=1
- type: subscribe
  options:
    url: https://xueyun.club/link/PQyKpjZ2PDlaqjwM?sub=1    
- type: subscribe
  options:
    url: https://nnn3ro.link/link/FxZILJnjXAWPwKpG?sub=1
- type: subscribe
  options:
    url: https://vpn-3.xyz/link/yjddDnnWjIFjn888?sub=1
- type: subscribe
  options:
    url: https://yukimo-link.xyz/link/90ixSszrq8125BOe?mu=1
- type: subscribe
  options:
    url: https://rss.paoluz.xyz/link/4k95cuWKQRFhprFm?sub=3&extend=1
- type: subscribe
  options:
    url: https://esucloud.com/link/Ms0rSs8opNU3cxdh?list=shadowrocket
- type: subscribe
  options:
    url: https://dingyue.suying666.info/link/z0XApyHKfdRp22kH?sub=1
- type: subscribe
  options:
    url: https://kitevpn.me/api/v1/client/subscribe?token=728eb7182f1504e6d2273e9015a8f9a1
- type: subscribe
  options:
    url: https://sub.starlink9527.xyz/api/v1/client/subscribe?token=c65f88c52825eba773f1541d025cce76
- type: subscribe
  options:
    url: https://sub.tomato91.cc/api/v1/client/subscribe?token=eafc52714775c7ded242c1c5e4232085
- type: subscribe
  options:
    url: http://www.paoche.cf/api/v1/client/subscribe?token=Trs5YhJddF26wMM6Vqf4f34UDBpzxkuF
- type: subscribe
  options:
    url: https://www.ov2rayo.top/api/v1/client/subscribe?token=3821f84ba4348ee9850582f3da676587
- type: subscribe
  options:
    url: https://www.gogocloud.icu/api/v1/client/subscribe?token=b4ef86e54459c4f6326b69dad5b98d8f
- type: subscribe
  options:
    url: https://yangzhichang.buzz/api/v1/client/subscribe?token=d8f3c77da6f83afc892eebe75054831e
- type: subscribe
  options:
    url: https://nekoneko.cloud/subscribe/4a4d4c80-4bd1-11eb-89e2-b1937530e5b7
- type: subscribe
  options:
    url: https://acrosscloud.icu//link/zuGvQj5PkKucpVP9?sub=1
- type: subscribe
  options:
    url: https://rss.cnrss.xyz/link/W9HNbTFobmNmqUVc?mu=2    
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocks
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray
- type: subscribe
  options:
    url: https://www.111003.ml//link/t18NMDfYwZAjdjOL?sub=1
- type: subscribe
  options:
    url: https://www.111003.ml//link/qnX4c3DPZ55rz2bv?sub=1
- type: subscribe
  options:
    url: https://www.111003.ml//link/JcPhNvNhhVYWrMtx?sub=1
- type: subscribe
  options:
    url: https://www.111003.ml//link/EDf0gn24rImopCIV?sub=1
- type: subscribe
  options:
    url: https://www.111003.ml//link/PnMfVArG0k6zV3hd?sub=1
- type: subscribe
  options:
    url: https://www.111003.ml//link/TpPuq3MbtjG3QSBJ?sub=1
- type: subscribe
  options:
    url: https://www.q88q.ga/link/xxEsNqPe5yyDKx6W?lt=2
- type: subscribe
  options:
    url: https://sketch.ide.wtf/OaksOwks
- type: subscribe
  options:
    url: http://www.forestjiasu.xyz/link/qTaWd5f6HNVKnk1k?mu=0
- type: subscribe
  options:
    url: https://sub.tomato91.cc/api/v1/client/subscribe?token=eafc52714775c7ded242c1c5e4232085
- type: subscribe
  options:
    url: https://cdn.jsdelivr.net/gh/fdaf123/KinhDown-dingyue/README.md
#订阅
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
    
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://suo.yt/IYe65QS
- type: clash
  options:
    url: https://suo.yt/5hbnQsQ   
- type: clash
  options:
    url: https://suo.yt/A3L0jab

# 某个网站抓取
- type: web-freessrxyz
  options:
