# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocks
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://inss.xyz/api/v1/client/subscribe?token=5029f7d14de3b1a8e39ed4d464b94f17
- type: subscribe
  options:
    url: https://sub.ssr.ac/link/gnFMjMWZxIB7YDMM?mu=1
- type: subscribe
  options:
    url: https://thirsty-galileo-395801.netlify.app
- type: subscribe
  options:
    url: https://sub.huojian987.site/link/rMbHxZusF1XGXXad?sub=3
- type: subscribe
  options:
    url: https://kkkssr.xyz//link/K5pwQwMMoeWguVNV?sub=1
- type: subscribe
  options:
    url: https://sub.prprc.xyz/link/heJdxuEK1sErsCEi?sub=1&class=3
- type: subscribe
  options:
    url: https://dingyue.suying666.info/link/qYopsRimEzj5qZwv?sub=1
- type: subscribe
  options:
    url: https://mnssr.cc/link/MAjMvCj8LiOceuSW?sub=1&extend=1
- type: subscribe
  options:
    url: https://xueyun.club/link/PQyKpjZ2PDlaqjwM?sub=1    
- type: subscribe
  options:
    url: https://nnn3ro.link/link/FxZILJnjXAWPwKpG?sub=1
- type: subscribe
  options:
    url: https://vpn-3.xyz/link/yjddDnnWjIFjn888?sub=1
- type: subscribe
  options:
    url: https://yukimo-link.xyz/link/90ixSszrq8125BOe?mu=1
- type: subscribe
  options:
    url: https://rss.paoluz.xyz/link/4k95cuWKQRFhprFm?sub=3&extend=1
- type: subscribe
  options:
    url: https://esucloud.com/link/Ms0rSs8opNU3cxdh?list=shadowrocket
- type: subscribe
  options:
    url: https://dingyue.suying666.info/link/z0XApyHKfdRp22kH?sub=1
- type: subscribe
  options:
    url: https://kitevpn.me/api/v1/client/subscribe?token=728eb7182f1504e6d2273e9015a8f9a1
- type: subscribe
  options:
    url: https://sub.starlink9527.xyz/api/v1/client/subscribe?token=c65f88c52825eba773f1541d025cce76
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
    
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
